name: 🐞 Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: Include the steps to reproduce this bug if applicable.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Where are you running VSCode? (Optional)
      options:
        - Windows
        - MacOS
        - Linux
        - Browser (Not yet supported)
    validations:
      required: false
  - type: dropdown
    attributes:
      label: What kind of LLM are you using? (Optional)
      description: Are you using an OpenAI model, a local LLM, or some other AI?
      options:
        - OpenAI
        - OpenAI w/ Azure
        - OpenAI w/ proxy
        - OpenRouter.ai
        - A local LLM (such as ollama)
        - A different cloud LLM
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context (Optional)
      description: Add any other context about the problem here. Please provide screenshots or screen recordings if possible.
    validations:
      required: false
